apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sri-app-ingress
  namespace: sri-staging
spec:
  # This field ensures the NGINX controller claims the resource 
  ingressClassName: nginx 
  rules:
  - host: staging.sri-app.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sri-app-service
            port:
              number: 80
