apiVersion: v1
kind: Service
metadata:
  name: sri-app-service
  namespace: sri-staging
spec:
  type: ClusterIP
  selector:
    app: sri-app  # Ensures traffic goes to pods with this label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Matches your Docker container port
