apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sri-app-ingress
  namespace: sri-qa
spec:
  # Links the Ingress to the NGINX controller for the QA environment
  ingressClassName: nginx 
  rules:
  - host: qa.sri-app.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sri-app-service
            port:
              number: 80
